# Generated by Django 5.1.7 on 2025-03-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('numero_bastidor', models.CharField(max_length=50, unique=True)),
                ('caracteristicas', models.TextField()),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=10)),
                ('datos_propietario_anterior', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido')], default='Disponible', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Vehículo', 'Vehículo'), ('Recambio', 'Recambio'), ('Accesorio', 'Accesorio')], max_length=20)),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.vehiculo')),
            ],
        ),
    ]
