# Generated by Django 5.0.2 on 2025-03-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default='2025-03-25'),
            preserve_default=False,
        ),
    ]
