# Generated by Django 5.0.2 on 2025-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
